// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="GetSearchContextImageRequest.cs">
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
//   Copyright (c) 2018 Aspose Pty Ltd.
=======
//   Copyright (c) 2018 Aspose.Imaging for Cloud
>>>>>>> SDK regenerated by CI server
=======
//   Copyright (c) 2018 Aspose.Imaging for Cloud
>>>>>>> SDK regenerated by CI server
=======
//   Copyright (c) 2018 Aspose.Imaging for Cloud
>>>>>>> ff98b60c39a2f6a40918f9c5c6942d9eabb4f764
// </copyright>
// <summary>
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Aspose.Imaging.Cloud.Sdk.Model.Requests 
{
  using Aspose.Imaging.Cloud.Sdk.Model; 

  /// <summary>
  /// Request model for <see cref="Aspose.Imaging.Cloud.Sdk.ImagingApi.GetSearchContextImage" /> operation.
  /// </summary>  
  public class GetSearchContextImageRequest  
  {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSearchContextImageRequest"/> class.
        /// </summary>        
        public GetSearchContextImageRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetSearchContextImageRequest"/> class.
        /// </summary>
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
        /// <param name="imageData">Input image</param>
>>>>>>> SDK regenerated by CI server
=======
>>>>>>> SDK regenerated by CI server
=======
>>>>>>> SDK regenerated by CI server
=======
>>>>>>> ff98b60c39a2f6a40918f9c5c6942d9eabb4f764
        /// <param name="searchContextId">Search context identifier.</param>
        /// <param name="imageId">Image identifier.</param>
        /// <param name="folder">Folder.</param>
        /// <param name="storage">Storage</param>
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        public GetSearchContextImageRequest(string searchContextId, string imageId, string folder = null, string storage = null)             
        {
=======
        public GetSearchContextImageRequest(System.IO.Stream imageData, string searchContextId, string imageId, string folder = null, string storage = null)             
        {
            this.imageData = imageData;
>>>>>>> SDK regenerated by CI server
=======
        public GetSearchContextImageRequest(string searchContextId, string imageId, string folder = null, string storage = null)             
        {
>>>>>>> SDK regenerated by CI server
=======
        public GetSearchContextImageRequest(string searchContextId, string imageId, string folder = null, string storage = null)             
        {
>>>>>>> SDK regenerated by CI server
=======
        public GetSearchContextImageRequest(string searchContextId, string imageId, string folder = null, string storage = null)             
        {
>>>>>>> ff98b60c39a2f6a40918f9c5c6942d9eabb4f764
            this.searchContextId = searchContextId;
            this.imageId = imageId;
            this.folder = folder;
            this.storage = storage;
        }
		
        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
        /// Input image
        /// </summary>  
        public System.IO.Stream imageData { get; set; }

        /// <summary>
>>>>>>> SDK regenerated by CI server
=======
>>>>>>> SDK regenerated by CI server
=======
>>>>>>> SDK regenerated by CI server
=======
>>>>>>> ff98b60c39a2f6a40918f9c5c6942d9eabb4f764
        /// Search context identifier.
        /// </summary>  
        public string searchContextId { get; set; }

        /// <summary>
        /// Image identifier.
        /// </summary>  
        public string imageId { get; set; }

        /// <summary>
        /// Folder.
        /// </summary>  
        public string folder { get; set; }

        /// <summary>
        /// Storage
        /// </summary>  
        public string storage { get; set; }
  }
}
